version: "3.8"
services:
  node-api:
    entrypoint: /bin/sh './entrypoint.sh'
    container_name: node-api
    build: .
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - mongo
    volumes:
      - ./:/app

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: example
      MONGO_INITDB_ROOT_PASSWORD: example
